"""The three country spreadsheet formats. They differ on purpose, as real ones do:
different sheet names, header rows, activity wording, cost-type codes, month formats,
percent scales and subtotal conventions."""

TEMPLATES = {
    "EC": dict(
        name="Formato Ecuador – Control de Costos versión 3",
        sheets=dict(summary="Resumen", cost="Costos mensuales", progress="Avance físico", production="Producción"),
        header_row=4,
        headers=("Cód.", "Actividad", "Tipo de costo"),
        budget_header="Presupuesto",
        total_header="Total",
        month_style="date",
        subtotal_prefix="Subtotal ",
        total_label="TOTAL GENERAL",
        progress_headers=("Cód.", "Actividad", "Tipo"),
        progress_labels=("Programado", "Real"),
        progress_scale=1,
        production_headers=("Mes", "Km soldados (acum.)", "Juntas soldadas (acum.)", "Reparaciones (acum.)"),
        cost_types={"MO": "Mano de obra", "EQ": "Equipos", "MAT": "Materiales", "SUB": "Subcontratos"},
        code_fmt="{i:02d}",
        summary_labels=("Proyecto:", "Cliente:", "Moneda:", "Corte:", "Monto de contrato:", "Margen de oferta:"),
        summary_table=("Cód.", "Actividad", "Presupuesto", "Costo real acumulado", "% Avance real"),
        title="CONDUTO — CONTROL DE COSTOS DE PROYECTO",
        cost_title="DETALLE MENSUAL DE COSTOS REALES",
        note="Datos sintéticos generados para demostración.",
        labels={
            "MOV": "Movilización y campamentos", "DDV": "Apertura de DDV", "ZAN": "Zanjeo", "TEN": "Tendido y curvado",
            "SOL": "Soldadura", "END": "Radiografía / END", "REV": "Revestimiento de juntas", "BAJ": "Bajado y tapado",
            "CRU": "Cruces especiales PHD", "PH": "Prueba hidrostática", "RES": "Restauración", "IND": "Indirectos",
            "EXC": "Movimiento de tierras", "CIM": "Obras de hormigón", "EST": "Estructura metálica",
            "MEC": "Montaje mecánico", "ELE": "Eléctrico e instrumentación", "PRU": "Pruebas y arranque",
        },
    ),
    "PE": dict(
        name="Formato Perú – Control Presupuestal versión 2",
        sheets=dict(summary="Resumen", cost="Costos", progress="Avance", production="Producción"),
        header_row=3,
        headers=("Partida", "Descripción", "Recurso"),
        budget_header="Ppto. (S/.)",
        total_header="Total",
        month_style="iso",
        subtotal_prefix=None,
        total_label="Total general",
        progress_headers=("Partida", "Descripción", "Prog./Real"),
        progress_labels=("Prog.", "Real"),
        progress_scale=100,
        production_headers=("Mes", "Km soldados (acum.)", "Juntas soldadas (acum.)", "Reparaciones (acum.)"),
        cost_types={"MO": "MO", "EQ": "EQ", "MAT": "MAT", "SUB": "SC"},
        code_fmt="{i:02d}.00",
        summary_labels=("Proyecto:", "Cliente:", "Moneda:", "Fecha de corte:", "Monto contratado:", "Margen ofertado:"),
        summary_table=("Partida", "Descripción", "Ppto. (S/.)", "Real acumulado (S/.)", "Avance real %"),
        title="CONDUTO PERÚ – CONTROL PRESUPUESTAL DE OBRA",
        cost_title="COSTOS REALES MENSUALES POR PARTIDA",
        note="Datos sintéticos generados para demostración.",
        labels={
            "MOV": "Movilización y desmovilización", "DDV": "Desbroce y conformación de DDV", "ZAN": "Excavación de zanja",
            "TEN": "Desfile y curvado de tubería", "SOL": "Soldadura de tubería", "END": "Inspección radiográfica",
            "REV": "Revestimiento de uniones", "BAJ": "Bajado y relleno de zanja", "CRU": "Cruces especiales (PHD)",
            "PH": "Prueba hidrostática", "RES": "Restauración y revegetación", "IND": "Gastos generales",
            "EXC": "Movimiento de tierras", "CIM": "Concreto armado", "EST": "Estructuras metálicas",
            "MEC": "Montaje electromecánico", "ELE": "Instalaciones eléctricas", "PRU": "Pruebas y comisionamiento",
        },
    ),
    "BR": dict(
        name="Planilha Brasil – Controle de Custos versão 1",
        sheets=dict(summary="Resumo", cost="Custos", progress="Avanço", production="Produção"),
        header_row=5,
        headers=("Item", "Atividade", "Natureza"),
        budget_header="Orçamento (R$)",
        total_header="Total",
        month_style="pt",
        subtotal_prefix="Subtotal – ",
        total_label="TOTAL",
        progress_headers=("Item", "Atividade", "Tipo"),
        progress_labels=("Previsto", "Realizado"),
        progress_scale=1,
        production_headers=("Mês", "Km soldados (acum.)", "Juntas soldadas (acum.)", "Reparos (acum.)"),
        cost_types={"MO": "Mão de obra", "EQ": "Equipamentos", "MAT": "Materiais", "SUB": "Subempreiteiros"},
        code_fmt="{i}",
        summary_labels=("Projeto:", "Cliente:", "Moeda:", "Data de corte:", "Valor do contrato:", "Margem da proposta:"),
        summary_table=("Item", "Atividade", "Orçamento (R$)", "Realizado acumulado (R$)", "% Avanço"),
        title="CONDUTO BRASIL — CONTROLE DE CUSTOS DA OBRA",
        cost_title="CUSTOS REALIZADOS MENSAIS",
        note="Dados sintéticos gerados para demonstração.",
        labels={
            "MOV": "Mobilização e canteiro", "DDV": "Abertura e limpeza de faixa", "ZAN": "Abertura de vala",
            "TEN": "Desfile e curvamento", "SOL": "Soldagem", "END": "Ensaios não destrutivos",
            "REV": "Revestimento de juntas", "BAJ": "Abaixamento e cobertura", "CRU": "Travessias especiais (MND)",
            "PH": "Teste hidrostático", "RES": "Recomposição ambiental", "IND": "Custos indiretos",
            "EXC": "Terraplenagem", "CIM": "Obras civis e concreto", "EST": "Estruturas metálicas",
            "MEC": "Montagem mecânica", "ELE": "Elétrica e instrumentação", "PRU": "Testes e comissionamento",
        },
    ),
}
